In [30]:
import numpy as np
from scipy.ndimage.interpolation import rotate

x = np.random.randint(0, 1000, size=[3, 3])
rotated = rotate(x, angle=20, reshape=False)

In [21]:
def decomp(mat):

    mat = list(mat)
    sym = []#np.empty(mat.shape[-2:])
    
    for m in mat:
        print('_________')
        print(type(m))
        mat_flip_x = np.fliplr(m)

        mat_flip_y = np.flipud(m)
        mat_flip_xy = np.fliplr(np.flipud(m))
        sum = m + mat_flip_x + mat_flip_y + mat_flip_xy

        mat_sum_rot_90 = np.rot90(sum)
        print((sum + mat_sum_rot_90) / 8)
        #sym = (sum + mat_sum_rot_90) / 8
        #anti_sym = mat - sym
        sym.append(((sum + mat_sum_rot_90) / 8))

    return np.array(sym) #, anti_sym


In [31]:
x

array([[616, 983, 776],
       [797, 407, 970],
       [988, 754, 638]])

In [32]:
rotated

array([[  0, 942,   0],
       [705, 407, 861],
       [  0, 852,   0]])

In [33]:
decomp([x])

_________
<class 'numpy.ndarray'>
[[754.5 876.  754.5]
 [876.  407.  876. ]
 [754.5 876.  754.5]]


array([[[754.5, 876. , 754.5],
        [876. , 407. , 876. ],
        [754.5, 876. , 754.5]]])

In [34]:
decomp([rotated])

_________
<class 'numpy.ndarray'>
[[  0. 840.   0.]
 [840. 407. 840.]
 [  0. 840.   0.]]


array([[[  0., 840.,   0.],
        [840., 407., 840.],
        [  0., 840.,   0.]]])